on: [ push, pull_request ]
name: test and build
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.15.x
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Install golangci-lint
        run: |
          go get github.com/golangci/golangci-lint/cmd/golangci-lint
      - name: Run linters
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          golangci-lint -E bodyclose,misspell,gocyclo,dupl,gofmt,golint,unconvert,goimports,depguard,gocritic,funlen,interfacer run

  test:
    strategy:
      matrix:
        go-version: [ 1.14.x, 1.15.x ]
        # platform: [ ubuntu-latest, macos-latest, windows-latest ]
        # cgo need extra dependencies
        platform: [ ubuntu-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        if: success()
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Run tests
        run: go test -v -covermode=count ./...

  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        if: success()
        uses: actions/setup-go@v1
        with:
          go-version: 1.14.x
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Calc coverage
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          go test -v -covermode=count -coverprofile=coverage.out ./...
      - name: Convert coverage to lcov
        uses: jandelgado/gcov2lcov-action@v1.0.0
        with:
          infile: coverage.out
          outfile: coverage.lcov
      - name: Coveralls
        uses: coverallsapp/github-action@v1.0.1
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: coverage.lcov

  build:
    runs-on: ubuntu-latest
    needs: [ lint, test ]
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.15.x
      - name: Checkout code
        uses: actions/checkout@v1
      - name: build
        run: |
          export GO111MODULE=on
          GOOS=windows GOARCH=amd64 go build -o bin/crontimer-windows-amd64.exe ./cmd/crontimer
          GOOS=linux GOARCH=amd64 go build -o bin/cromtimer-linux-amd64 ./cmd/crontimer
          GOOS=darwin GOARCH=amd64 go build -o bin/cromtimer-darwin-amd64 ./cmd/crontimer

          GOOS=linux GOARCH=amd64 go build -o bin/apkindexer-linux-amd64 ./cmd/apkindexer


      - name: upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: binaries
          path: bin/
